### ISSUE TITLE
not getting color wheel on webpage

### ISSUE THREAD

**Issue by rajbadri** [jmbussat/WS2812_ESP8266#1] opened 2016-01-10 18:47 UTC
i am using your sketch on a esp8266-e nodemcu 1 and this what i get when i go to the webpage.

Please guide

Thanks

<img width="739" alt="screen shot 2016-01-11 at 12 11 16 am" src="https://cloud.githubusercontent.com/assets/5882232/12223274/7bf220b6-b7f8-11e5-9c94-dd1aedd77d03.png">

**Comment by jmbussat** [comment] 2016-01-11 00:10
Couple of things come to mind:
- I'm running the sketch with the Arduino for ESP8266 environment (my ESP8266 is not flashed with nodemcu). My understanding is that if you use nodemcu, you have to communicate with the ESP8266 using Lua commands.
- What happens if you go? (using the IP address shown on your attachment): http://192.168.1.235/out

Hope this helps,

**Comment by rajbadri** [comment] 2016-01-11 07:09
i am using arduino ide 1.6.5 on my nodemcu esp8266 hardware

**Comment by jmbussat** [comment] 2016-01-11 08:28
Hi, 

Sorry, I had forgotten to upload the last fix of my code. 
- The fact that you are using the arduino environment should have taken care of everything.
- I had forgotten to change the handle_root() function to send data as "text/html" instead of "text/plain"
- If you use the updated code, you should now see a link instead of html code
- Typing in the address: http://192.168.1.235/out should have and should still show you the color wheel

Let me know if you are still experiencing the issue.
Thanks,

**Comment by rajbadri** [comment] 2016-01-11 15:05
now it does not compile asks for "html_header.h"

**Comment by rajbadri** [comment] 2016-01-11 17:22
hi
i have started using your new code and now get a colour wheel when i go to the webpage, i have connected the data pin to "gpio 0" but the led's don't glow or change colour. The colour wheel sends the codes when i click on it and appear to work. but led's remain off.
i am using two WS2812 lets soldered and are working perfectly with other sketches.
![img_20160111_224817](https://cloud.githubusercontent.com/assets/5882232/12240895/f9d4c444-b8b5-11e5-9873-989288a1fc25.jpg)

**Comment by jmbussat** [comment] 2016-01-12 22:00
For some reason, your last message shows up in my email but not here.

What other sketch did you try with your setup?

When using my sketch, did you update the number of LED (NUM_PIX on line 9)? I could see cases where if you have less LEDs than NUM_PIX, they would not light up properly.

Otherwise, I would have said maybe the logic level out of the ESP12 is not good enough (I'm pushing the limit with the WS2812 being powered on 5V while the ESP is sending 3.3V logic levels - The WS2812 can be picky about the quality of the logic level, that said, it is usually true for the first LED but should be ok for the rest since each LED has a buffer...). I have ordered my own nodemcu but I won't receive it in less than two weeks.

**Comment by rajbadri** [comment] 2016-01-14 17:33
hi 
i am now able to get the colour wheel when i go to the webpage and when i click different areas of the wheel it appears to send the codes but the colours in the ws2812  led constant and don't change i am attaching a picture. I am using a 4 x ws2812 strip (which is working fine with other sketches) and i have modified " #define NUM_PIX 4 " in your sketch.

![img_20160114_230011](https://cloud.githubusercontent.com/assets/5882232/12332140/e300335c-bb12-11e5-9669-7f4e1a5153d9.jpg)

**Comment by jmbussat** [comment] 2016-01-14 18:24
Hi,

Could you try by adding a wire between the ground of the Nodemcu board and
the ground of the WS2812?

Thanks,

**Comment by rajbadri** [comment] 2016-01-14 19:41
i have done that and still same problem

**Comment by rajbadri** [comment] 2016-01-15 09:10
do i have to follow this process ( i am using the html_header.h bundled with your code)

"I developped the Javascript code separately from the ESP code. You can find it in the file colorwheel.html. The html file is converted into a C "header" file via the following command:

cat colorwheel.html  | sed -e "s/\"/'/g" | sed -e '/^\s_$/d' | sed -e 's/._/\"&\"/g' > colorwheel.h

This replace all double quotes with single quotes, removes empty lines and encloses each line in double quotes. The resulting file is then copied as html_header.h and the following is added at the begining to make it a constant definition:

const char\* html_header =
A semicolon has to be added at the end."

**Comment by jmbussat** [comment] 2016-01-20 03:43
You don't have to use this step if you are using the html_header.h bundled with my code.
Still trying to figure out what is going on on your side. 
When you are using other sketches, are they all using GPIO0 to communicate with the WS2812 or a different one? I noticed that on the nodemcu board, there are a lot of other things attached to GPIO0 and I am wondering if that could cause problem.
I'm still waiting for my nodemcu board to come. It should arrive in a few days.

**Comment by jmbussat** [comment] 2016-02-18 01:56
![img_9106](https://cloud.githubusercontent.com/assets/16263699/13131249/17342db2-d59f-11e5-94e8-dd656e7d762f.JPG)
Hello,
Got my nodemcu board today.
Like in your case, it doesn't behave as expected: I can only change the color of the first WS2812 of the string regardless of the number of pixel used in the code.
I tried a different GPIO in case it could be caused by the extra logic that is attached to GPIO0 but it didn't help.
Tomorrow, I'll try adding a buffer between the Nodemcu board and the WS2812 string. If it doesn't help, I'll compare the signals generated by the ESP12 on the Nodemcu with the ones generated by the ESP01 to try to understand what is going on.

**Comment by jmbussat** [comment] 2016-02-18 22:31
This was a mistake from my side. The hardware is ok. I had changed the loop that updates the WS2812.
When I change back line 84 to scan the full string, everything works as expected.
I tried: with USB power or using a battery pack. Also tried GPIO0 and GPIO5.
![img_9121](https://cloud.githubusercontent.com/assets/16263699/13160373/da8ae7fe-d64b-11e5-9b84-6b34dbd7edf4.JPG)
![img_9123](https://cloud.githubusercontent.com/assets/16263699/13160385/f8e884d6-d64b-11e5-9a2b-63d7d08c7b7f.JPG)
![img_9124](https://cloud.githubusercontent.com/assets/16263699/13160407/2058dfe8-d64c-11e5-96ae-38250ff55eaa.JPG)

Let me know how things are on your side.
Thanks,

**Comment by jmbussat** [comment] 2017-05-24 09:00
Closing issue after over one year without activity since last update.

**Closed as completed by jmbussat** 2017-05-24 09:00 UTC
